name: Publish package

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  rubygems:
    name: Publish to RubyGems
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true
      - run: gem build nvoip-ruby.gemspec
      - run: gem push nvoip-*.gem
        env:
          GEM_HOST_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
